spring:
  application:
    name: facebookdemoapp

server:
  address: localhost
  port: 7070
  
security:
  oauth2:
    client:
      clientId: 313939739201773
      clientSecret: 62715b1d33008f55c478a9ae4c80fbea
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me