spring:
    application:
        name: resource-server
        
server:
  port: 8000
  
security:
    oauth2:
        resource:
            filter-order: 3 
            jwt: 
                key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz9OYWoEPhYkpxJaMAG0qlIoQfTyvrWB8V51lSejhujeytpdXgcrtiKx7OqBDvfyoac8o8C0MDp/uA6qltislEvtpj3Uoa+PLOnuF3WHZxioh1B2hDBWrVXsM4KDDbi3DcdKroOusUTJp49ZNp/N/ogCdrkkPSGhtZqWnM3iBGarL0yBRczksiMjHIXQ6yukybjci0a4n5vwDRHQrsa+/HFODF5y5WImnaTUM+xs5BHlX9ITWJpbFZnbsba2ch7823iX2k6S+oSoWJoPWlbs7UqQAitKW6eHXcxK4GGUA+aoWrJOUK4CkOQRRkLZS1wO9MIv7fcFS2hL9WiOd/qZ9twIDAQAB-----END PUBLIC KEY-----
