server:
  port: 8000
security:
    oauth2:
        resource:
            filter-order: 3 
            jwt: 
                key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5N53sfPXhzKvMjcRlG2CgHq8+oZu/jyq9UOhpeyAn149C2aMlPXBHBCOKPtoLByj7q4VuVV9bKsPk7LQ1mylgYtoW6ATisWJ3ZC3X1tApwVDaHsaNU/XjtBc/h3jmXVGKwf8N+r2MLAUpkONyENS0FP9XuhaN5H7SnD/i9JSM1CAqYPY9RNFxJ9cnmdnYpBocCPdwNGqHGHAq+5Gjl+MvDL4LutkVgKGseeRVt4sRXyAZLaCvE0NnL+h2iVryPQXZd7n74rDQAcW9Wez69uwVN8ml3JRhvLujSkAi7h2ml9amVblpt5Hw7i0+PTAFSGvLTTGC19jYBGn4genUeXRYwIDAQAB-----END PUBLIC KEY-----