spring:
    application:
        name: authorization-server
        
server:
  address: localhost
  port: 6000
        

config:
    oauth2:
        clientid: hareram
        clientSecret: hareram@singh
